//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace EduUruk.Models.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthRes
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthRes()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduUruk.Models.Resources.AuthRes", typeof(AuthRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم اضافة الصفحة بنجاح.
        /// </summary>
        public static string AddingSuccessfully
        {
            get
            {
                return ResourceManager.GetString("AddingSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم اضافة قائمة بنجاح.
        /// </summary>
        public static string AddingSuccessfully1
        {
            get
            {
                return ResourceManager.GetString("AddingSuccessfully1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اضافة صفحة.
        /// </summary>
        public static string AddingTitle
        {
            get
            {
                return ResourceManager.GetString("AddingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اضافة قائمة جديدة.
        /// </summary>
        public static string AddingTitle1
        {
            get
            {
                return ResourceManager.GetString("AddingTitle1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم التطبيق.
        /// </summary>
        public static string ApplicationId
        {
            get
            {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار التطبيق.
        /// </summary>
        public static string ApplicationIdRequired
        {
            get
            {
                return ResourceManager.GetString("ApplicationIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم القائمة بالعربية.
        /// </summary>
        public static string ArabicGroupName
        {
            get
            {
                return ResourceManager.GetString("ArabicGroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم  القائمة بالعربية لا يتجاوز 35  حرف.
        /// </summary>
        public static string ArabicGroupNameLength
        {
            get
            {
                return ResourceManager.GetString("ArabicGroupNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال اسم  القائمة بالعربية.
        /// </summary>
        public static string ArabicGroupNameRequired
        {
            get
            {
                return ResourceManager.GetString("ArabicGroupNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الاسم بالعربي.
        /// </summary>
        public static string ArabicName
        {
            get
            {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم الصفحة بالعربية.
        /// </summary>
        public static string ArabicPageName
        {
            get
            {
                return ResourceManager.GetString("ArabicPageName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم الصفحة بالعربية لا يتجاوز 35  حرف.
        /// </summary>
        public static string ArabicPageNameLength
        {
            get
            {
                return ResourceManager.GetString("ArabicPageNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال اسم الصفحة بالعربية.
        /// </summary>
        public static string ArabicPageNameRequired
        {
            get
            {
                return ResourceManager.GetString("ArabicPageNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اضافة صفحة جديدة.
        /// </summary>
        public static string BtnAdd
        {
            get
            {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اضافة قائمة جديدة.
        /// </summary>
        public static string BtnAdd1
        {
            get
            {
                return ResourceManager.GetString("BtnAdd1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التفعيل.
        /// </summary>
        public static string CanActive
        {
            get
            {
                return ResourceManager.GetString("CanActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الاضافة.
        /// </summary>
        public static string CanCreate
        {
            get
            {
                return ResourceManager.GetString("CanCreate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الحذف.
        /// </summary>
        public static string CanDelete
        {
            get
            {
                return ResourceManager.GetString("CanDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التعديل.
        /// </summary>
        public static string CanEdit
        {
            get
            {
                return ResourceManager.GetString("CanEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الطباعة.
        /// </summary>
        public static string CanPrint
        {
            get
            {
                return ResourceManager.GetString("CanPrint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الاستعراض.
        /// </summary>
        public static string CanSelect
        {
            get
            {
                return ResourceManager.GetString("CanSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من حذف الصفحة :.
        /// </summary>
        public static string DeleteMessage
        {
            get
            {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من حذف القائمة:.
        /// </summary>
        public static string DeleteMessage1
        {
            get
            {
                return ResourceManager.GetString("DeleteMessage1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حذف صفحة.
        /// </summary>
        public static string DeleteTitle
        {
            get
            {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حذف قائمة.
        /// </summary>
        public static string DeleteTitle1
        {
            get
            {
                return ResourceManager.GetString("DeleteTitle1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم حذف الصفحة بنجاح.
        /// </summary>
        public static string DeletingSuccessfully
        {
            get
            {
                return ResourceManager.GetString("DeletingSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم حذف القائمة بنجاح.
        /// </summary>
        public static string DeletingSuccessfully1
        {
            get
            {
                return ResourceManager.GetString("DeletingSuccessfully1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الصفحة بنجاح.
        /// </summary>
        public static string EditingSuccessfully
        {
            get
            {
                return ResourceManager.GetString("EditingSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم تعديل القائمة بنجاح.
        /// </summary>
        public static string EditingSuccessfully1
        {
            get
            {
                return ResourceManager.GetString("EditingSuccessfully1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعديل صفحة.
        /// </summary>
        public static string EditTitle
        {
            get
            {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعديل القائمة.
        /// </summary>
        public static string EditTitle1
        {
            get
            {
                return ResourceManager.GetString("EditTitle1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم  القائمة بالانجليزية.
        /// </summary>
        public static string EnglishGroupName
        {
            get
            {
                return ResourceManager.GetString("EnglishGroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم  القائمة بالانجليزية لا يتجاوز 35 حرف.
        /// </summary>
        public static string EnglishGroupNameLength
        {
            get
            {
                return ResourceManager.GetString("EnglishGroupNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال اسم  القائمة بالانجليزية.
        /// </summary>
        public static string EnglishGroupNameRequired
        {
            get
            {
                return ResourceManager.GetString("EnglishGroupNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم الصفحة بالانجليزية.
        /// </summary>
        public static string EnglishPageName
        {
            get
            {
                return ResourceManager.GetString("EnglishPageName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم الصفحة بالانجليزية لا يتجاوز 35 حرف.
        /// </summary>
        public static string EnglishPageNameLength
        {
            get
            {
                return ResourceManager.GetString("EnglishPageNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال اسم الصفحة بالانجليزية.
        /// </summary>
        public static string EnglishPageNameRequired
        {
            get
            {
                return ResourceManager.GetString("EnglishPageNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to أيقونة القائمة.
        /// </summary>
        public static string GroupIco
        {
            get
            {
                return ResourceManager.GetString("GroupIco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to أيقونة القائمة لا يتجاوز 15 حرف.
        /// </summary>
        public static string GroupIcoLength
        {
            get
            {
                return ResourceManager.GetString("GroupIcoLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال أيقونة القائمة.
        /// </summary>
        public static string GroupIcoRequired
        {
            get
            {
                return ResourceManager.GetString("GroupIcoRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم القائمة.
        /// </summary>
        public static string GroupID
        {
            get
            {
                return ResourceManager.GetString("GroupID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تسلسل.
        /// </summary>
        public static string GroupID1
        {
            get
            {
                return ResourceManager.GetString("GroupID1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم القائمة.
        /// </summary>
        public static string GroupName
        {
            get
            {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string GroupNameTextField
        {
            get
            {
                return ResourceManager.GetString("GroupNameTextField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ArabicGroupName.
        /// </summary>
        public static string GroupNameTextField1
        {
            get
            {
                return ResourceManager.GetString("GroupNameTextField1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ترتيب القائمة.
        /// </summary>
        public static string GroupOrder
        {
            get
            {
                return ResourceManager.GetString("GroupOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الترتيب في القائمة.
        /// </summary>
        public static string PageGroupIndex
        {
            get
            {
                return ResourceManager.GetString("PageGroupIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الصفحة.
        /// </summary>
        public static string PageID
        {
            get
            {
                return ResourceManager.GetString("PageID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تسلسل.
        /// </summary>
        public static string PageID1
        {
            get
            {
                return ResourceManager.GetString("PageID1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ترتيب الصفحة.
        /// </summary>
        public static string PageIndex
        {
            get
            {
                return ResourceManager.GetString("PageIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تريب داخل القائمة.
        /// </summary>
        public static string PageIndex1
        {
            get
            {
                return ResourceManager.GetString("PageIndex1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ادخل ترتيب الصفحة.
        /// </summary>
        public static string PageIndexRequired
        {
            get
            {
                return ResourceManager.GetString("PageIndexRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم الصفحة.
        /// </summary>
        public static string PageName
        {
            get
            {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ArabicPageName.
        /// </summary>
        public static string PageNameTextField
        {
            get
            {
                return ResourceManager.GetString("PageNameTextField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الصفحات.
        /// </summary>
        public static string PageTitle
        {
            get
            {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعريف القوائم.
        /// </summary>
        public static string PageTitle1
        {
            get
            {
                return ResourceManager.GetString("PageTitle1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رابط الصفحة.
        /// </summary>
        public static string PageURL
        {
            get
            {
                return ResourceManager.GetString("PageURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رابط الصفحة لا يتجاوز 65 حرف.
        /// </summary>
        public static string PageURLLength
        {
            get
            {
                return ResourceManager.GetString("PageURLLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال رابط الصفحة.
        /// </summary>
        public static string PageURLRequired
        {
            get
            {
                return ResourceManager.GetString("PageURLRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف الصفحة لوجود بيانات مرتبطة.
        /// </summary>
        public static string RelatedDataException
        {
            get
            {
                return ResourceManager.GetString("RelatedDataException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف  القائمة لوجود بيانات مرتبطة.
        /// </summary>
        public static string RelatedDataException1
        {
            get
            {
                return ResourceManager.GetString("RelatedDataException1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الصلاحية.
        /// </summary>
        public static string RoleId
        {
            get
            {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الصلاحية.
        /// </summary>
        public static string RoleName
        {
            get
            {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
    }
}
