//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduUruk.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduUruk.Models.Resources.BusRes", typeof(BusRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الاضافة بنجاح.
        /// </summary>
        public static string AddingSuccessfully {
            get {
                return ResourceManager.GetString("AddingSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة جديدة.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الايام.
        /// </summary>
        public static string ConutDay {
            get {
                return ResourceManager.GetString("ConutDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الساعات.
        /// </summary>
        public static string Conuthours {
            get {
                return ResourceManager.GetString("Conuthours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منشئ بواسطة.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانشاء.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الحذف بنجاح.
        /// </summary>
        public static string DeletingSuccessfully {
            get {
                return ResourceManager.GetString("DeletingSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الادارة المعينة.
        /// </summary>
        public static string DepartmentId {
            get {
                return ResourceManager.GetString("DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentIdRequired.
        /// </summary>
        public static string DepartmentIdRequired {
            get {
                return ResourceManager.GetString("DepartmentIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الادارة.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الادارة مطلوب إدخاله.
        /// </summary>
        public static string DepartmentNameRequired {
            get {
                return ResourceManager.GetString("DepartmentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات الادارة.
        /// </summary>
        public static string DepartmentNote {
            get {
                return ResourceManager.GetString("DepartmentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentNoteLength.
        /// </summary>
        public static string DepartmentNoteLength {
            get {
                return ResourceManager.GetString("DepartmentNoteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentNoteRequired.
        /// </summary>
        public static string DepartmentNoteRequired {
            get {
                return ResourceManager.GetString("DepartmentNoteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentProgress.
        /// </summary>
        public static string DepartmentProgress {
            get {
                return ResourceManager.GetString("DepartmentProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل لا يتجاوز 500 حرف.
        /// </summary>
        public static string DetailsLength {
            get {
                return ResourceManager.GetString("DetailsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل مطلوب ادخالها.
        /// </summary>
        public static string DetailsRequired {
            get {
                return ResourceManager.GetString("DetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية التعديل بنجاح.
        /// </summary>
        public static string EditingSuccessfully {
            get {
                return ResourceManager.GetString("EditingSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع التصعيد.
        /// </summary>
        public static string EscalationTypeID {
            get {
                return ResourceManager.GetString("EscalationTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InboxStatusId.
        /// </summary>
        public static string InboxStatusId {
            get {
                return ResourceManager.GetString("InboxStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة الوارد منها المعاملة.
        /// </summary>
        public static string InstitutionName {
            get {
                return ResourceManager.GetString("InstitutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة الوارد منها المعاملة لا يتجاوز 100 حرف.
        /// </summary>
        public static string InstitutionNameLength {
            get {
                return ResourceManager.GetString("InstitutionNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة الوارد منها المعاملة مطلوب إدخالها.
        /// </summary>
        public static string InstitutionNameRequired {
            get {
                return ResourceManager.GetString("InstitutionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخة.
        /// </summary>
        public static string IsCC {
            get {
                return ResourceManager.GetString("IsCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات إدارة المتابعة.
        /// </summary>
        public static string MeetingsNote {
            get {
                return ResourceManager.GetString("MeetingsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات لا تتجاوز 500 حرف.
        /// </summary>
        public static string MeetingsNoteLength {
            get {
                return ResourceManager.GetString("MeetingsNoteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات مطلوب ادخالها.
        /// </summary>
        public static string MeetingsNoteRequired {
            get {
                return ResourceManager.GetString("MeetingsNoteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeetingsTaskId.
        /// </summary>
        public static string MeetingsTaskId {
            get {
                return ResourceManager.GetString("MeetingsTaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعديل بواسطة.
        /// </summary>
        public static string ModifyBy {
            get {
                return ResourceManager.GetString("ModifyBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التعديل.
        /// </summary>
        public static string ModifyDate {
            get {
                return ResourceManager.GetString("ModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التنبيه.
        /// </summary>
        public static string NotificationDate {
            get {
                return ResourceManager.GetString("NotificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع التنبيه.
        /// </summary>
        public static string NotificationTypeId {
            get {
                return ResourceManager.GetString("NotificationTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم نوع التنبيه.
        /// </summary>
        public static string NotificationTypeName {
            get {
                return ResourceManager.GetString("NotificationTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم نوع التنبيه لا يتجاوز 65 حرف.
        /// </summary>
        public static string NotificationTypeNameLength {
            get {
                return ResourceManager.GetString("NotificationTypeNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم نوع التنبيه مطلوب ادخاله.
        /// </summary>
        public static string NotificationTypeNameRequired {
            get {
                return ResourceManager.GetString("NotificationTypeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنظمة.
        /// </summary>
        public static string OrgnaizationId {
            get {
                return ResourceManager.GetString("OrgnaizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنظمة.
        /// </summary>
        public static string OrgnaizationName {
            get {
                return ResourceManager.GetString("OrgnaizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنظمة مطلوب ادخاله.
        /// </summary>
        public static string OrgnaizationNameRequired {
            get {
                return ResourceManager.GetString("OrgnaizationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حامل المشعل.
        /// </summary>
        public static string PersonId {
            get {
                return ResourceManager.GetString("PersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات حامل المشعل.
        /// </summary>
        public static string PersonNote {
            get {
                return ResourceManager.GetString("PersonNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات لا تتجاوز 500 حرف.
        /// </summary>
        public static string PersonNoteLength {
            get {
                return ResourceManager.GetString("PersonNoteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات مطلوب ادخالها.
        /// </summary>
        public static string PersonNoteRequired {
            get {
                return ResourceManager.GetString("PersonNoteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة الانجاز.
        /// </summary>
        public static string progress {
            get {
                return ResourceManager.GetString("progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        public static string SendType {
            get {
                return ResourceManager.GetString("SendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنظمة مطلوب ادخاله.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectRequired.
        /// </summary>
        public static string SubjectRequired {
            get {
                return ResourceManager.GetString("SubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بداية المهمة.
        /// </summary>
        public static string TaskDate {
            get {
                return ResourceManager.GetString("TaskDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بداية المهمة مطلوب أدخاله.
        /// </summary>
        public static string TaskDateRequired {
            get {
                return ResourceManager.GetString("TaskDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ نهاية المهمة.
        /// </summary>
        public static string TaskEndDate {
            get {
                return ResourceManager.GetString("TaskEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ نهاية المهمة مطلوب ادخاله.
        /// </summary>
        public static string TaskEndDateRequired {
            get {
                return ResourceManager.GetString("TaskEndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهمة.
        /// </summary>
        public static string TaskId {
            get {
                return ResourceManager.GetString("TaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskIdRequired.
        /// </summary>
        public static string TaskIdRequired {
            get {
                return ResourceManager.GetString("TaskIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة.
        /// </summary>
        public static string TaskNo {
            get {
                return ResourceManager.GetString("TaskNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة لا يتجاوز 65 حرف.
        /// </summary>
        public static string TaskNoLength {
            get {
                return ResourceManager.GetString("TaskNoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة مطلوب ادخاله.
        /// </summary>
        public static string TaskNoRequired {
            get {
                return ResourceManager.GetString("TaskNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات المهمة.
        /// </summary>
        public static string TaskNote {
            get {
                return ResourceManager.GetString("TaskNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskNoteLength.
        /// </summary>
        public static string TaskNoteLength {
            get {
                return ResourceManager.GetString("TaskNoteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskNoteRequired.
        /// </summary>
        public static string TaskNoteRequired {
            get {
                return ResourceManager.GetString("TaskNoteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة الاهمية.
        /// </summary>
        public static string TaskPriorityId {
            get {
                return ResourceManager.GetString("TaskPriorityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة الاهمية مطلوب ادخالها.
        /// </summary>
        public static string TaskPriorityIdRequired {
            get {
                return ResourceManager.GetString("TaskPriorityIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة الاهمية.
        /// </summary>
        public static string TaskPriorityName {
            get {
                return ResourceManager.GetString("TaskPriorityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة الاهمية مطلوب إدخالها.
        /// </summary>
        public static string TaskPriorityNameRequired {
            get {
                return ResourceManager.GetString("TaskPriorityNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المهمة.
        /// </summary>
        public static string TaskStatusId {
            get {
                return ResourceManager.GetString("TaskStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المهمة.
        /// </summary>
        public static string TaskStatusName {
            get {
                return ResourceManager.GetString("TaskStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المهمة مطلوب ادخالها.
        /// </summary>
        public static string TaskStatusNameRequired {
            get {
                return ResourceManager.GetString("TaskStatusNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان المهمة.
        /// </summary>
        public static string TaskSubject {
            get {
                return ResourceManager.GetString("TaskSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان المهمة لا يتجاوز 100 حرف.
        /// </summary>
        public static string TaskSubjectLength {
            get {
                return ResourceManager.GetString("TaskSubjectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان المهمة مطلوب ادخاله.
        /// </summary>
        public static string TaskSubjectRequired {
            get {
                return ResourceManager.GetString("TaskSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المهمة.
        /// </summary>
        public static string TaskTypeId {
            get {
                return ResourceManager.GetString("TaskTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المهمة مطلوب دخاله.
        /// </summary>
        public static string TaskTypeIdRequired {
            get {
                return ResourceManager.GetString("TaskTypeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المهمة.
        /// </summary>
        public static string TaskTypeName {
            get {
                return ResourceManager.GetString("TaskTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المهمة مطلوب ادخاله.
        /// </summary>
        public static string TaskTypeNameRequired {
            get {
                return ResourceManager.GetString("TaskTypeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان لا يتجاوز 100 حرف.
        /// </summary>
        public static string TitleLength {
            get {
                return ResourceManager.GetString("TitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان مطلوب ادخاله.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرسل له.
        /// </summary>
        public static string Userid {
            get {
                return ResourceManager.GetString("Userid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرسل له مطلوب ادخاله.
        /// </summary>
        public static string UseridRequired {
            get {
                return ResourceManager.GetString("UseridRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
    }
}
