//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduUruk.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduUruk.Models.Resources.GeneralRes", typeof(GeneralRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط حاليا هل تود التعطيل.
        /// </summary>
        public static string ActiveText {
            get {
                return ResourceManager.GetString("ActiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطبيقات الأنظمة.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المجموعة بالعربي.
        /// </summary>
        public static string ArabicGroupName {
            get {
                return ResourceManager.GetString("ArabicGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string ArabicLanguageTitle {
            get {
                return ResourceManager.GetString("ArabicLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string asideDirection {
            get {
                return ResourceManager.GetString("asideDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الاساسية.
        /// </summary>
        public static string BasicDataMenuTitle {
            get {
                return ResourceManager.GetString("BasicDataMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        public static string BodyCSS {
            get {
                return ResourceManager.GetString("BodyCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تـراجع.
        /// </summary>
        public static string BtnCancelText {
            get {
                return ResourceManager.GetString("BtnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غلق.
        /// </summary>
        public static string BtnCloseText {
            get {
                return ResourceManager.GetString("BtnCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد الحذف.
        /// </summary>
        public static string BtnDeleteText {
            get {
                return ResourceManager.GetString("BtnDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        public static string BtnDownload {
            get {
                return ResourceManager.GetString("BtnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string BtnEditText {
            get {
                return ResourceManager.GetString("BtnEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معاينة للتأكيد.
        /// </summary>
        public static string BtnHotelsPreviewText {
            get {
                return ResourceManager.GetString("BtnHotelsPreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسعير.
        /// </summary>
        public static string BtnHotelsPricingText {
            get {
                return ResourceManager.GetString("BtnHotelsPricingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة عرض السعر.
        /// </summary>
        public static string BtnHotelsSubmitText {
            get {
                return ResourceManager.GetString("BtnHotelsSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        public static string BtnNewText {
            get {
                return ResourceManager.GetString("BtnNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        public static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفندق التالي.
        /// </summary>
        public static string BtnNextHotelText {
            get {
                return ResourceManager.GetString("BtnNextHotelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-arrow-left.
        /// </summary>
        public static string BtnNextIcon {
            get {
                return ResourceManager.GetString("BtnNextIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        public static string BtnNextText {
            get {
                return ResourceManager.GetString("BtnNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خيارات.
        /// </summary>
        public static string BtnOptions {
            get {
                return ResourceManager.GetString("BtnOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        public static string BtnPrevious {
            get {
                return ResourceManager.GetString("BtnPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-arrow-right.
        /// </summary>
        public static string BtnPreviousIcon {
            get {
                return ResourceManager.GetString("BtnPreviousIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إتمام.
        /// </summary>
        public static string BtnPublish {
            get {
                return ResourceManager.GetString("BtnPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث.
        /// </summary>
        public static string BtnRefresh {
            get {
                return ResourceManager.GetString("BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string BtnRemoveText {
            get {
                return ResourceManager.GetString("BtnRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string BtnSaveText {
            get {
                return ResourceManager.GetString("BtnSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string BtnSearchText {
            get {
                return ResourceManager.GetString("BtnSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        public static string BtnSend {
            get {
                return ResourceManager.GetString("BtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إبدأ.
        /// </summary>
        public static string BtnStart {
            get {
                return ResourceManager.GetString("BtnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتماد.
        /// </summary>
        public static string BtnSubmit {
            get {
                return ResourceManager.GetString("BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتماد.
        /// </summary>
        public static string BtnSubmitText {
            get {
                return ResourceManager.GetString("BtnSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string BtnYes {
            get {
                return ResourceManager.GetString("BtnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموذج تغيير كلمة السر.
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        public static string ControlBodyCSS {
            get {
                return ResourceManager.GetString("ControlBodyCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤشرات.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي المستخدمين.
        /// </summary>
        public static string DashboardTotalUsersTitle {
            get {
                return ResourceManager.GetString("DashboardTotalUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معطل حاليا هل تود التنشيط.
        /// </summary>
        public static string DesactiveText {
            get {
                return ResourceManager.GetString("DesactiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايميل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المجموعة بالانجليزي.
        /// </summary>
        public static string EnglishGroupName {
            get {
                return ResourceManager.GetString("EnglishGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الانجليزية.
        /// </summary>
        public static string EnglishLanguageTitle {
            get {
                return ResourceManager.GetString("EnglishLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء معالجة البيانات.
        /// </summary>
        public static string ErrorWhileProcessingData {
            get {
                return ResourceManager.GetString("ErrorWhileProcessingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء حفظ البيانات.
        /// </summary>
        public static string ErrorWhileSaving {
            get {
                return ResourceManager.GetString("ErrorWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جار المعالجة.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تتم العملية راجع الدعم الفني..
        /// </summary>
        public static string GeneralExceptionMessage {
            get {
                return ResourceManager.GetString("GeneralExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعة.
        /// </summary>
        public static string GroupID {
            get {
                return ResourceManager.GetString("GroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفقي | اتجاه القائمة الرئيسية.
        /// </summary>
        public static string hrizontal {
            get {
                return ResourceManager.GetString("hrizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LangaugeTitle {
            get {
                return ResourceManager.GetString("LangaugeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري التحميل ......
        /// </summary>
        public static string LoadingTitle {
            get {
                return ResourceManager.GetString("LoadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة.
        /// </summary>
        public static string NavigationMenuTitle {
            get {
                return ResourceManager.GetString("NavigationMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية لإجراء العملية.
        /// </summary>
        public static string NoPermissionsMessage {
            get {
                return ResourceManager.GetString("NoPermissionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلاحيات المستخدمين.
        /// </summary>
        public static string PermissionTitle {
            get {
                return ResourceManager.GetString("PermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جار المعالجة.
        /// </summary>
        public static string ProccessTitle {
            get {
                return ResourceManager.GetString("ProccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصي.
        /// </summary>
        public static string ProfileMenuTitle {
            get {
                return ResourceManager.GetString("ProfileMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar.
        /// </summary>
        public static string Ratelanguage {
            get {
                return ResourceManager.GetString("Ratelanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحكم.
        /// </summary>
        public static string RecordControl {
            get {
                return ResourceManager.GetString("RecordControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب الادخال.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء عدم تجاوز الحد المسموح.
        /// </summary>
        public static string Required_Length {
            get {
                return ResourceManager.GetString("Required_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعدادات.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجاح العملية.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انقر هنا لإختيار الصورة .
        /// </summary>
        public static string UploadText {
            get {
                return ResourceManager.GetString("UploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المستخدم.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string UsersPageTitle {
            get {
                return ResourceManager.GetString("UsersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رأسي | اتجاه القائمة الرئيسية.
        /// </summary>
        public static string vertical {
            get {
                return ResourceManager.GetString("vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا  لوحة الإدارة !.
        /// </summary>
        public static string Welcome_to_Admin_Panel {
            get {
                return ResourceManager.GetString("Welcome_to_Admin_Panel", resourceCulture);
            }
        }
    }
}
