//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace EduUruk.Models.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SysModelRes
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysModelRes()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduUruk.Models.Resources.SysModelRes", typeof(SysModelRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ التنفيذ الفعلي.
        /// </summary>
        public static string Acutal_End_Date
        {
            get
            {
                return ResourceManager.GetString("Acutal_End_Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ البدء الفعلي.
        /// </summary>
        public static string Acutal_Start_Date
        {
            get
            {
                return ResourceManager.GetString("Acutal_Start_Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم اضافة  مستخدم بنجاح.
        /// </summary>
        public static string AddingSuccessfully
        {
            get
            {
                return ResourceManager.GetString("AddingSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اضافة .
        /// </summary>
        public static string AddingTitle
        {
            get
            {
                return ResourceManager.GetString("AddingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string ApplicationId
        {
            get
            {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application is required.
        /// </summary>
        public static string ApplicationIdRequired
        {
            get
            {
                return ResourceManager.GetString("ApplicationIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ اصدار التعميد.
        /// </summary>
        public static string Approval_Date
        {
            get
            {
                return ResourceManager.GetString("Approval_Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم التعميد.
        /// </summary>
        public static string Approve_No
        {
            get
            {
                return ResourceManager.GetString("Approve_No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الوصف بالعربية.
        /// </summary>
        public static string ArabicDescription
        {
            get
            {
                return ResourceManager.GetString("ArabicDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الوصف لا يتجاوز 165 حرف.
        /// </summary>
        public static string ArabicDescriptionLength
        {
            get
            {
                return ResourceManager.GetString("ArabicDescriptionLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الوصف.
        /// </summary>
        public static string ArabicDescriptionRequired
        {
            get
            {
                return ResourceManager.GetString("ArabicDescriptionRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arabic Menu.
        /// </summary>
        public static string ArabicGroupName
        {
            get
            {
                return ResourceManager.GetString("ArabicGroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arabic Menu is limited to 35 symbols.
        /// </summary>
        public static string ArabicGroupNameLength
        {
            get
            {
                return ResourceManager.GetString("ArabicGroupNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arabic Menu is Required.
        /// </summary>
        public static string ArabicGroupNameRequired
        {
            get
            {
                return ResourceManager.GetString("ArabicGroupNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arabic page name.
        /// </summary>
        public static string ArabicPageName
        {
            get
            {
                return ResourceManager.GetString("ArabicPageName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arabic page is limited to 35 symbols.
        /// </summary>
        public static string ArabicPageNameLength
        {
            get
            {
                return ResourceManager.GetString("ArabicPageNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arabic page is required.
        /// </summary>
        public static string ArabicPageNameRequired
        {
            get
            {
                return ResourceManager.GetString("ArabicPageNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم مستخدم.
        /// </summary>
        public static string ArabicUserName
        {
            get
            {
                return ResourceManager.GetString("ArabicUserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم لا يتجاوز 65 حرف.
        /// </summary>
        public static string ArabicUserNameLength
        {
            get
            {
                return ResourceManager.GetString("ArabicUserNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال اسم مستخدم.
        /// </summary>
        public static string ArabicUserNameRequired
        {
            get
            {
                return ResourceManager.GetString("ArabicUserNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  أزرق | لون المظهر.
        /// </summary>
        public static string blue
        {
            get
            {
                return ResourceManager.GetString("blue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اضافة جديد.
        /// </summary>
        public static string BtnAdd
        {
            get
            {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حفظ التعديلات.
        /// </summary>
        public static string BtnChangePssword
        {
            get
            {
                return ResourceManager.GetString("BtnChangePssword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to غلق.
        /// </summary>
        public static string BtnClose
        {
            get
            {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التفعيل.
        /// </summary>
        public static string CanActive
        {
            get
            {
                return ResourceManager.GetString("CanActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الاضافة.
        /// </summary>
        public static string CanCreate
        {
            get
            {
                return ResourceManager.GetString("CanCreate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الحذف.
        /// </summary>
        public static string CanDelete
        {
            get
            {
                return ResourceManager.GetString("CanDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التعديل.
        /// </summary>
        public static string CanEdit
        {
            get
            {
                return ResourceManager.GetString("CanEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الطباعة.
        /// </summary>
        public static string CanPrint
        {
            get
            {
                return ResourceManager.GetString("CanPrint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الاستعراض.
        /// </summary>
        public static string CanSelect
        {
            get
            {
                return ResourceManager.GetString("CanSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التصنيفات.
        /// </summary>
        public static string Categories_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("Categories_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        public static string Category
        {
            get
            {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        public static string Category_Name
        {
            get
            {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نموذج تغيير كلمة المرور.
        /// </summary>
        public static string ChangePasswordForm
        {
            get
            {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم تعديل كلمة المرور بنجاح.
        /// </summary>
        public static string ChangePasswordSuccessfully
        {
            get
            {
                return ResourceManager.GetString("ChangePasswordSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعديل كلمة المرور.
        /// </summary>
        public static string ChangePasswordTitle
        {
            get
            {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الصفة.
        /// </summary>
        public static string CharacterName
        {
            get
            {
                return ResourceManager.GetString("CharacterName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الصفات.
        /// </summary>
        public static string Characters_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("Characters_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اللون.
        /// </summary>
        public static string Color
        {
            get
            {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نسبة الإنجاز.
        /// </summary>
        public static string Complate_Precent
        {
            get
            {
                return ResourceManager.GetString("Complate_Precent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور الجديدة.
        /// </summary>
        public static string ConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير مطابقة.
        /// </summary>
        public static string ConfirmPasswordCompare
        {
            get
            {
                return ResourceManager.GetString("ConfirmPasswordCompare", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاكيد كلمة السر تعدت الحد المسموح.
        /// </summary>
        public static string ConfirmPasswordExceed
        {
            get
            {
                return ResourceManager.GetString("ConfirmPasswordExceed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور لا يتجاوز 16 حرف.
        /// </summary>
        public static string ConfirmPasswordLength
        {
            get
            {
                return ResourceManager.GetString("ConfirmPasswordLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال تأكيد  كلمة المرور الجديدة.
        /// </summary>
        public static string ConfirmPasswordRequired
        {
            get
            {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ انتهاء التعاقد.
        /// </summary>
        public static string ContractExpirationDate
        {
            get
            {
                return ResourceManager.GetString("ContractExpirationDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال التاريخ.
        /// </summary>
        public static string ContractExpirationDateRequired
        {
            get
            {
                return ResourceManager.GetString("ContractExpirationDateRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المقاول.
        /// </summary>
        public static string Contractor
        {
            get
            {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المقاول.
        /// </summary>
        public static string Contractor_Name
        {
            get
            {
                return ResourceManager.GetString("Contractor_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المقاولين.
        /// </summary>
        public static string Contractors_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("Contractors_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم بالعربية.
        /// </summary>
        public static string Createdby
        {
            get
            {
                return ResourceManager.GetString("Createdby", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to انشأ المستخدم في وقت.
        /// </summary>
        public static string CreatedTime
        {
            get
            {
                return ResourceManager.GetString("CreatedTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية.
        /// </summary>
        public static string CurrentPassword
        {
            get
            {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور لا يتجاوز 16 حرف.
        /// </summary>
        public static string CurrentPasswordExceed
        {
            get
            {
                return ResourceManager.GetString("CurrentPasswordExceed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال كلمة المرور الحالية.
        /// </summary>
        public static string CurrentPasswordRequired
        {
            get
            {
                return ResourceManager.GetString("CurrentPasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date
        {
            get
            {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اللغة الافتراضية.
        /// </summary>
        public static string DefaultLang
        {
            get
            {
                return ResourceManager.GetString("DefaultLang", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اللغة يجب ان لا تتعدى 35.
        /// </summary>
        public static string DefaultLangLength
        {
            get
            {
                return ResourceManager.GetString("DefaultLangLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لابد من اختيار اللغة.
        /// </summary>
        public static string DefaultLangRequired
        {
            get
            {
                return ResourceManager.GetString("DefaultLangRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اتجاه القائمة الرئيسية.
        /// </summary>
        public static string DefaultMenu
        {
            get
            {
                return ResourceManager.GetString("DefaultMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار اتجاه القائمة الرئيسية.
        /// </summary>
        public static string DefaultMenuRequired
        {
            get
            {
                return ResourceManager.GetString("DefaultMenuRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لون المظهر.
        /// </summary>
        public static string DefaultTheme
        {
            get
            {
                return ResourceManager.GetString("DefaultTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لون المظهر يجب ان لا يتعدى 35.
        /// </summary>
        public static string DefaultThemeLength
        {
            get
            {
                return ResourceManager.GetString("DefaultThemeLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لابد من اختيار لون المظهر.
        /// </summary>
        public static string DefaultThemeRequired
        {
            get
            {
                return ResourceManager.GetString("DefaultThemeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من حذف المستخدم:.
        /// </summary>
        public static string DeleteMessage
        {
            get
            {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حذف مستخدم.
        /// </summary>
        public static string DeleteTitle
        {
            get
            {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم حذف مستخدم بنجاح.
        /// </summary>
        public static string DeletingSuccessfully
        {
            get
            {
                return ResourceManager.GetString("DeletingSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الادارة.
        /// </summary>
        public static string DepartmentID
        {
            get
            {
                return ResourceManager.GetString("DepartmentID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نبذة.
        /// </summary>
        public static string Desc
        {
            get
            {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ما تم انجازه.
        /// </summary>
        public static string Done_Note
        {
            get
            {
                return ResourceManager.GetString("Done_Note", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string DT
        {
            get
            {
                return ResourceManager.GetString("DT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم تعديل مستخدم بنجاح.
        /// </summary>
        public static string EditingSuccessfully
        {
            get
            {
                return ResourceManager.GetString("EditingSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الملف الشخصي بنجاح.
        /// </summary>
        public static string EditProfileSuccessfully
        {
            get
            {
                return ResourceManager.GetString("EditProfileSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعديل الملف الشخصي.
        /// </summary>
        public static string EditProfileTitle
        {
            get
            {
                return ResourceManager.GetString("EditProfileTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعديل مستخدم.
        /// </summary>
        public static string EditTitle
        {
            get
            {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to البريد الكتروني .
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to البريد الاكتروني غير صحيح.
        /// </summary>
        public static string EmailInvalid
        {
            get
            {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to البريد الاكتروني لا يتجاوز 35 حرف.
        /// </summary>
        public static string EmailLength
        {
            get
            {
                return ResourceManager.GetString("EmailLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال البريد الالكتروني.
        /// </summary>
        public static string EmailRequired
        {
            get
            {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ انتهاء التنفيذ.
        /// </summary>
        public static string End_Date
        {
            get
            {
                return ResourceManager.GetString("End_Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الوصف بالانجليزية.
        /// </summary>
        public static string EnglishDescription
        {
            get
            {
                return ResourceManager.GetString("EnglishDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الوصف لا يتجاوز 165 حرف.
        /// </summary>
        public static string EnglishDescriptionLength
        {
            get
            {
                return ResourceManager.GetString("EnglishDescriptionLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الوصف.
        /// </summary>
        public static string EnglishDescriptionRequired
        {
            get
            {
                return ResourceManager.GetString("EnglishDescriptionRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English Menu Name.
        /// </summary>
        public static string EnglishGroupName
        {
            get
            {
                return ResourceManager.GetString("EnglishGroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English Menu Name is limited to 35 symbols.
        /// </summary>
        public static string EnglishGroupNameLength
        {
            get
            {
                return ResourceManager.GetString("EnglishGroupNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English Menu Name is required.
        /// </summary>
        public static string EnglishGroupNameRequired
        {
            get
            {
                return ResourceManager.GetString("EnglishGroupNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English page name.
        /// </summary>
        public static string EnglishPageName
        {
            get
            {
                return ResourceManager.GetString("EnglishPageName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English page name is limited to 35 symbols.
        /// </summary>
        public static string EnglishPageNameLength
        {
            get
            {
                return ResourceManager.GetString("EnglishPageNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English page name is required.
        /// </summary>
        public static string EnglishPageNameRequired
        {
            get
            {
                return ResourceManager.GetString("EnglishPageNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم بالانجليزية.
        /// </summary>
        public static string EnglishUserName
        {
            get
            {
                return ResourceManager.GetString("EnglishUserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم لا يتجاوز 65 حرف.
        /// </summary>
        public static string EnglishUserNameLength
        {
            get
            {
                return ResourceManager.GetString("EnglishUserNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال اسم المستخدم.
        /// </summary>
        public static string EnglishUserNameRequired
        {
            get
            {
                return ResourceManager.GetString("EnglishUserNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ فتح المظاريف.
        /// </summary>
        public static string Envelope_Date
        {
            get
            {
                return ResourceManager.GetString("Envelope_Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نسيت بيانات الحساب.
        /// </summary>
        public static string ForgetAccountPassword
        {
            get
            {
                return ResourceManager.GetString("ForgetAccountPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور.
        /// </summary>
        public static string ForgetPageTitle
        {
            get
            {
                return ResourceManager.GetString("ForgetPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إعادة تعيين كلمة المرور.
        /// </summary>
        public static string ForgetPasswordTitle
        {
            get
            {
                return ResourceManager.GetString("ForgetPasswordTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رمادي | لون المظهر.
        /// </summary>
        public static string gray
        {
            get
            {
                return ResourceManager.GetString("gray", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to أخضر | لون المظهر.
        /// </summary>
        public static string green
        {
            get
            {
                return ResourceManager.GetString("green", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu Icon.
        /// </summary>
        public static string GroupIco
        {
            get
            {
                return ResourceManager.GetString("GroupIco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Icon is limited to 15 symbols.
        /// </summary>
        public static string GroupIcoLength
        {
            get
            {
                return ResourceManager.GetString("GroupIcoLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Icon is required.
        /// </summary>
        public static string GroupIcoRequired
        {
            get
            {
                return ResourceManager.GetString("GroupIcoRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string GroupID
        {
            get
            {
                return ResourceManager.GetString("GroupID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu Name.
        /// </summary>
        public static string GroupName
        {
            get
            {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ArabicGroupName.
        /// </summary>
        public static string GroupNameTextField
        {
            get
            {
                return ResourceManager.GetString("GroupNameTextField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu Order.
        /// </summary>
        public static string GroupOrder
        {
            get
            {
                return ResourceManager.GetString("GroupOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الضيف.
        /// </summary>
        public static string Guest
        {
            get
            {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مرحبا .
        /// </summary>
        public static string HelloText
        {
            get
            {
                return ResourceManager.GetString("HelloText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id
        {
            get
            {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ انتهاء الهوية.
        /// </summary>
        public static string IdentityExpirationDate
        {
            get
            {
                return ResourceManager.GetString("IdentityExpirationDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال التاريخ.
        /// </summary>
        public static string IdentityExpirationDateRequired
        {
            get
            {
                return ResourceManager.GetString("IdentityExpirationDateRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to جار العمل.
        /// </summary>
        public static string InProgress_Note
        {
            get
            {
                return ResourceManager.GetString("InProgress_Note", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية غير صحيحة.
        /// </summary>
        public static string InvalidCurrentPasword
        {
            get
            {
                return ResourceManager.GetString("InvalidCurrentPasword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني لا يخص مستخدم.
        /// </summary>
        public static string InvalideMailData
        {
            get
            {
                return ResourceManager.GetString("InvalideMailData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بيانات الدخول غير صحيحة.
        /// </summary>
        public static string InvalidLoginData
        {
            get
            {
                return ResourceManager.GetString("InvalidLoginData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرابط غير صحيح او صلاحية الرابط منتهيه.
        /// </summary>
        public static string InvalidResetToken
        {
            get
            {
                return ResourceManager.GetString("InvalidResetToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الداعي.
        /// </summary>
        public static string Inviter
        {
            get
            {
                return ResourceManager.GetString("Inviter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اخر تسجيل دخول.
        /// </summary>
        public static string LastLogin
        {
            get
            {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حالة اخر تسجيل دخول.
        /// </summary>
        public static string LastLoginStatus
        {
            get
            {
                return ResourceManager.GetString("LastLoginStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الموقع.
        /// </summary>
        public static string Location_Name
        {
            get
            {
                return ResourceManager.GetString("Location_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المواقع.
        /// </summary>
        public static string Locations_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("Locations_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الحساب معطل.
        /// </summary>
        public static string LockedOutAccountMessage
        {
            get
            {
                return ResourceManager.GetString("LockedOutAccountMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        public static string LoginTitle
        {
            get
            {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سجل الاحداث.
        /// </summary>
        public static string Logs_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("Logs_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المدير.
        /// </summary>
        public static string ManagerID
        {
            get
            {
                return ResourceManager.GetString("ManagerID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حدد المدير ....
        /// </summary>
        public static string ManagerPlaceholder
        {
            get
            {
                return ResourceManager.GetString("ManagerPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المدة.
        /// </summary>
        public static string Meeting_Duration
        {
            get
            {
                return ResourceManager.GetString("Meeting_Duration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الوقت.
        /// </summary>
        public static string Meeting_Time
        {
            get
            {
                return ResourceManager.GetString("Meeting_Time", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الموعد.
        /// </summary>
        public static string Meeting_Title
        {
            get
            {
                return ResourceManager.GetString("Meeting_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الحضور.
        /// </summary>
        public static string MeetingAttend
        {
            get
            {
                return ResourceManager.GetString("MeetingAttend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حالة الحضور.
        /// </summary>
        public static string MeetingAttends_Status
        {
            get
            {
                return ResourceManager.GetString("MeetingAttends_Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الحضور.
        /// </summary>
        public static string MeetingAttendss_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("MeetingAttendss_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المواعيد.
        /// </summary>
        public static string Meetings_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("Meetings_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        public static string Mobile
        {
            get
            {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال غير صحيح.
        /// </summary>
        public static string MobileInvalid
        {
            get
            {
                return ResourceManager.GetString("MobileInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم  الجوال لا يتجاوز 20 حرف.
        /// </summary>
        public static string MobileLength
        {
            get
            {
                return ResourceManager.GetString("MobileLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال رقم الجوال.
        /// </summary>
        public static string MobileRequired
        {
            get
            {
                return ResourceManager.GetString("MobileRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NewData.
        /// </summary>
        public static string NewData
        {
            get
            {
                return ResourceManager.GetString("NewData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        public static string NewPassword
        {
            get
            {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة السر الجديدة تعدت الحد المسموح.
        /// </summary>
        public static string NewPasswordExceed
        {
            get
            {
                return ResourceManager.GetString("NewPasswordExceed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال كلمة المرور الجديدة.
        /// </summary>
        public static string NewPasswordRequired
        {
            get
            {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Note
        {
            get
            {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OldData.
        /// </summary>
        public static string OldData
        {
            get
            {
                return ResourceManager.GetString("OldData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور القديمة.
        /// </summary>
        public static string OldPassword
        {
            get
            {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        public static string OprType
        {
            get
            {
                return ResourceManager.GetString("OprType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الترتيب.
        /// </summary>
        public static string OrderNumber
        {
            get
            {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PageGroupIndex.
        /// </summary>
        public static string PageGroupIndex
        {
            get
            {
                return ResourceManager.GetString("PageGroupIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مجموعة الصفحات.
        /// </summary>
        public static string PageGroups_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("PageGroups_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string PageID
        {
            get
            {
                return ResourceManager.GetString("PageID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ترتيب الصفحة.
        /// </summary>
        public static string PageIndex
        {
            get
            {
                return ResourceManager.GetString("PageIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ادخل ترتيب الصفحة.
        /// </summary>
        public static string PageIndexRequired
        {
            get
            {
                return ResourceManager.GetString("PageIndexRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page name.
        /// </summary>
        public static string PageName
        {
            get
            {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EnglishPageName.
        /// </summary>
        public static string PageNameTextField
        {
            get
            {
                return ResourceManager.GetString("PageNameTextField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الصفحات.
        /// </summary>
        public static string Pages_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("Pages_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مستخدمي النظام.
        /// </summary>
        public static string PageTitle
        {
            get
            {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        public static string PageTitle_Create
        {
            get
            {
                return ResourceManager.GetString("PageTitle_Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string PageTitle_Delete
        {
            get
            {
                return ResourceManager.GetString("PageTitle_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string PageTitle_Edit
        {
            get
            {
                return ResourceManager.GetString("PageTitle_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string PageURL
        {
            get
            {
                return ResourceManager.GetString("PageURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL is limited to 15 symbols.
        /// </summary>
        public static string PageURLLength
        {
            get
            {
                return ResourceManager.GetString("PageURLLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL is required.
        /// </summary>
        public static string PageURLRequired
        {
            get
            {
                return ResourceManager.GetString("PageURLRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المدير التابع له.
        /// </summary>
        public static string ParentID
        {
            get
            {
                return ResourceManager.GetString("ParentID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور لا تفي المتطلبات.
        /// </summary>
        public static string PasswordExpression
        {
            get
            {
                return ResourceManager.GetString("PasswordExpression", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور من 8 الى 16 خانة.
        /// </summary>
        public static string PasswordLength
        {
            get
            {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال كلمة المرور.
        /// </summary>
        public static string PasswordRequired
        {
            get
            {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions
        {
            get
            {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to صورة المستخدم.
        /// </summary>
        public static string Photo
        {
            get
            {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المبلغ.
        /// </summary>
        public static string Price
        {
            get
            {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مستوى الأهميات.
        /// </summary>
        public static string Priorities_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("Priorities_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مستوى الأهمية.
        /// </summary>
        public static string Priority
        {
            get
            {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مستوى الأهمية.
        /// </summary>
        public static string Priority_Name
        {
            get
            {
                return ResourceManager.GetString("Priority_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المهمة.
        /// </summary>
        public static string Project_Name
        {
            get
            {
                return ResourceManager.GetString("Project_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المهمة.
        /// </summary>
        public static string ProjectHead_Name
        {
            get
            {
                return ResourceManager.GetString("ProjectHead_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المهام.
        /// </summary>
        public static string ProjectHeads
        {
            get
            {
                return ResourceManager.GetString("ProjectHeads", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المهام الرئيسية.
        /// </summary>
        public static string ProjectHeads_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("ProjectHeads_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المهام.
        /// </summary>
        public static string Projectss_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("Projectss_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مسار الانجاز.
        /// </summary>
        public static string ProjectSubTasks
        {
            get
            {
                return ResourceManager.GetString("ProjectSubTasks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مسار إنجاز المهمة.
        /// </summary>
        public static string ProjectSubTasks_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("ProjectSubTasks_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        public static string ProjectType
        {
            get
            {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        public static string ProjectType_Name
        {
            get
            {
                return ResourceManager.GetString("ProjectType_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to أحمر | لون المظهر.
        /// </summary>
        public static string red
        {
            get
            {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ التسجيل.
        /// </summary>
        public static string RegistrationDate
        {
            get
            {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال تاريخ التسجيل.
        /// </summary>
        public static string RegistrationDateRequired
        {
            get
            {
                return ResourceManager.GetString("RegistrationDateRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف  المستخدم لوجود بيانات مرتبطة.
        /// </summary>
        public static string RelatedDataException
        {
            get
            {
                return ResourceManager.GetString("RelatedDataException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لايمكن الحذف لوجود بيانات مرتبطة.
        /// </summary>
        public static string RelatedDataException1
        {
            get
            {
                return ResourceManager.GetString("RelatedDataException1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        public static string RememberMe
        {
            get
            {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مطلوب الادخال.
        /// </summary>
        public static string Required
        {
            get
            {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا يتجاوز الغدد المسموح فيه.
        /// </summary>
        public static string Required_Length
        {
            get
            {
                return ResourceManager.GetString("Required_Length", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اعادة تعيين كلمة المرور.
        /// </summary>
        public static string ResetPageTitle
        {
            get
            {
                return ResourceManager.GetString("ResetPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لإعادة تعيين كلمة المرور قم بالضغط على الرابط أدناه.
        /// </summary>
        public static string ResetPasswordMailMessage
        {
            get
            {
                return ResourceManager.GetString("ResetPasswordMailMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرابط صالح لمدة 30 دقيقة فقط.
        /// </summary>
        public static string ResetPasswordMailMessageFooter
        {
            get
            {
                return ResourceManager.GetString("ResetPasswordMailMessageFooter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Secuirty System : إعادة تعيين كلمة المرور.
        /// </summary>
        public static string ResetPasswordMailSubject
        {
            get
            {
                return ResourceManager.GetString("ResetPasswordMailSubject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المجموعة.
        /// </summary>
        public static string RoleID
        {
            get
            {
                return ResourceManager.GetString("RoleID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد المجموعة.
        /// </summary>
        public static string RoleIDRequired
        {
            get
            {
                return ResourceManager.GetString("RoleIDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حدد المجموعة ....
        /// </summary>
        public static string RoleIDSelectTitle
        {
            get
            {
                return ResourceManager.GetString("RoleIDSelectTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        public static string Roles
        {
            get
            {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حدد صلاحية واحده على الأقل.
        /// </summary>
        public static string RolesRequired
        {
            get
            {
                return ResourceManager.GetString("RolesRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعذر إرسال رابط إعادة تعيين كلمة المرور.
        /// </summary>
        public static string SendResetPasswordFailed
        {
            get
            {
                return ResourceManager.GetString("SendResetPasswordFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم إرسال رابط إعادة تعيين كلمة المرور .
        /// </summary>
        public static string SendResetPasswordSuccessfully
        {
            get
            {
                return ResourceManager.GetString("SendResetPasswordSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المهندس المشرف.
        /// </summary>
        public static string SName
        {
            get
            {
                return ResourceManager.GetString("SName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ بدء العمل.
        /// </summary>
        public static string Start_Date
        {
            get
            {
                return ResourceManager.GetString("Start_Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status
        {
            get
            {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status_Name
        {
            get
            {
                return ResourceManager.GetString("Status_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الحالات.
        /// </summary>
        public static string Statuss_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("Statuss_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TableName.
        /// </summary>
        public static string TableName
        {
            get
            {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اللقب.
        /// </summary>
        public static string TitleName
        {
            get
            {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الالقاب.
        /// </summary>
        public static string Titles_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("Titles_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type
        {
            get
            {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عدل المستخدم في وقت.
        /// </summary>
        public static string UpdatdTime
        {
            get
            {
                return ResourceManager.GetString("UpdatdTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عدل المستخدم بواسطة.
        /// </summary>
        public static string UpdatedBy
        {
            get
            {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to أنقر لإضافة صورة.
        /// </summary>
        public static string UploadText
        {
            get
            {
                return ResourceManager.GetString("UploadText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UserFullName
        {
            get
            {
                return ResourceManager.GetString("UserFullName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم المستخدم.
        /// </summary>
        public static string UserID
        {
            get
            {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم المستخدم لا يتعدى 15 حرف.
        /// </summary>
        public static string UserIDLength
        {
            get
            {
                return ResourceManager.GetString("UserIDLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حدد المستخدم ....
        /// </summary>
        public static string UserIDPlaceholder
        {
            get
            {
                return ResourceManager.GetString("UserIDPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حدد المستخدم.
        /// </summary>
        public static string UserIDRequired
        {
            get
            {
                return ResourceManager.GetString("UserIDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string UserIds
        {
            get
            {
                return ResourceManager.GetString("UserIds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UserName
        {
            get
            {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم لا يتجاوز 25 خانة.
        /// </summary>
        public static string UserNameLength
        {
            get
            {
                return ResourceManager.GetString("UserNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال اسم المستخدم.
        /// </summary>
        public static string UserNameRequired
        {
            get
            {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ArabicUserName.
        /// </summary>
        public static string UserNameTextField
        {
            get
            {
                return ResourceManager.GetString("UserNameTextField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مجموعة صلاحية.
        /// </summary>
        public static string UserRoles_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("UserRoles_PageTitle_Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعيين صلاحيات المستخدم.
        /// </summary>
        public static string UserRolesTitle
        {
            get
            {
                return ResourceManager.GetString("UserRolesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string Users_PageTitle_Index
        {
            get
            {
                return ResourceManager.GetString("Users_PageTitle_Index", resourceCulture);
            }
        }
    }
}
